# -*- coding: utf-8 -*-
"""Lab Task 1:(2021-3_60_288)Random Student ID Selector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQG8XpLz71EiCDSGA5kCZIihAh83SgTR

Lab Task 1: Random Student ID Selector
"""

 import random

def read_student_ids(filename):

    try:
        with open(filename, 'r') as file:
            # Reads the file line by line and strips leading/trailing whitespace
            student_ids = [line.strip() for line in file if line.strip()]
        return student_ids
    except FileNotFoundError:
        print(f"Error: The file '{filename}' was not found.")
        return []

def select_students_for_viva(student_ids):

    viva_counter = 1
    remaining_students = student_ids[:]

    while remaining_students:
        selected_student = random.choice(remaining_students)
        print(f"Viva #{viva_counter}: {selected_student}")
        remaining_students.remove(selected_student)
        viva_counter += 1

    print("\nAll students have been selected for the viva.")

def main():

    filename = 'student_id.txt'


    student_ids = read_student_ids(filename)


    if student_ids:
        while True:

            select_students_for_viva(student_ids)
            print("\nResetting student list for the next round...\n")


            user_input = input("Press Enter to start a new round of viva selections, or type 'exit' to quit: ")
            if user_input.lower() == 'exit':
                print("Exiting the program. Goodbye!")
                break

if __name__ == "__main__":
    main()
